services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chariot
    ports:
      - "5432:5432"
    volumes:
      - db_disk:/var/lib/postgresql/data

  api:
    build: .
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: chariot
      DB_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure

volumes:
  db_disk:

